modLoader="javafml"
loaderVersion="[0,)" # At least version 1 of the loader
license="MIT"
[[mods]]
modId="numismatics_subscriptions"
version="1.0.0"
displayName="Create: Numismatics - Subscriptions"
description="Extension for Create: Numismatics"
